import * as React from "react";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import theme from "@/app/theme";

import Head from "next/head";

import Header from "./_components/header/Header";
// import Navigation from "@/app/_components/navigation/Navigation";
import Footer from "@/app/_components/footer/Footer";

import "@/app/_styles/globals.css";

export const metadata = {
  title: {
    template: "کمک رسان ایران | %s",
    default: "کمک رسان ایران",
  },
  description: "Iran SOS, Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <Head>
        <meta name="description" content={metadata.description} />
      </Head>
      <body className="text-primary-600 min-h-screen flex flex-col">
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <ThemeProvider theme={theme}>
            {/* CssBaseline kickstart an elegant, consistent, and simple baseline to build upon. */}
            <CssBaseline />
            <Header />
            <div className="flex-1 px-8 py-12">
              <main className="max-w-7xl mx-auto">{children}</main>
            </div>
            <Footer />
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
